apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  labels:
    app: ghost-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ngnix-pod
      app: demo-nginx
  template:
    metadata:
      labels:
        name: ngnix-pod
        app: demo-nginx
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80