apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webserver-pod
      app: webserver-app
  template:
    metadata:
      labels:
        name: webserver-pod
        app: webserver-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80