apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache-deployment-label
spec:
  replicas: 5
  selector:
    matchLabels:
      name: webserver-pod
      app: webserver-app
  template:
    metadata:
      labels:
        name: webserver-pod
        app: webserver-app
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80